#!/bin/bash


function trap_ctrlc ()
{
	sig=$1

	echo "sig: ${sig}"

	kill -${sig} "$child"
}

trap "trap_ctrlc TERM" TERM
trap "trap_ctrlc INT" INT

TS_NODE_FILES=true; TS_NODE_TRANSPILE_ONLY=true; node -r ts-node/register ./src/bin/facilitator.ts $@ 2>&1 &

child=$!
wait "$child"
