const EntityGraphQueries: Record<string, string> = {
  stakeRequesteds: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'stakeRequesteds(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

  stakeIntentDeclareds: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'stakeIntentDeclareds(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

  stateRootAvailables: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'stateRootAvailables(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

  stakeIntentConfirmeds: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'stakeIntentConfirmeds(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

  gatewayProvens: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'gatewayProvens(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

  stakeProgresseds: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'stakeProgresseds(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

  mintProgresseds: 'query ($contractAddress: String!, $uts: BigInt!, $skip: BigInt!, $limit:'
  + ' BigInt!) {\n'
  + 'mintProgresseds(skip: $skip, first:$limit, orderDirection: asc, where: {contractAddress:'
  + ' $contractAddress, uts_gt: $uts}, '
  + '    orderDirection: asc,'
  + '    limit: 100) {\n'
  + '    id\n'
  + '    amount\n'
  + '    gasPrice\n'
  + '    gasLimit\n'
  + '    staker\n'
  + '    gateway\n'
  + '    stakeRequestHash\n'
  + '    nonce\n'
  + '    beneficiary\n'
  + '    contractAddress\n'
  + '    blockNumber\n'
  + '    uts\n'
  + '  }\n'
  + '}',

};

export default EntityGraphQueries;
